spring:
   application:
      # 定义应用名
      name: fruit-config
   cloud:
     config:
        server:
          git:
            # 配置文件分支 ==》现在的默认分支是 main ，以前是master
            default-label: main
            # 配置文件所在仓库
            uri: https://github.com/CZ89-S3/Fruits/
            # 配置文件所在根目录
            search-paths: /C-S3-P-fruit
            # 公共仓库不需要配置用户名和密码
            username: 
            password: 

server:
   # Eureka 服务器的默认端口是：8761
   port: 9000

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
