server:
   port: 0

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
         
spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      #&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1/hilofruits?useSSL=false
      username: root
      password: a
      
      
logging:
   level:
      com.yc: debug